import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import Navbar from "@/components/Nav/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={``}>
        <NextThemesProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
        >
          <main className="">{children}</main>
        </NextThemesProvider>
      </body>
    </html>
  );
}
